version: '3'

services:
  # Service proxy seul avec l'image construite localement
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OVH_TOKEN_ENDPOINT=${OVH_TOKEN_ENDPOINT}
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - webui_network

  # Service OpenWebUI avec l'image officielle
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: always
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://proxy:8000/
      - RAG_EMBEDDING_MODEL=local
      - DISABLE_OLLAMA_STREAMING=true
      - OPENAI_API_KEY=dummy
      - WEBUI_AUTH=TRUE
      - WEBUI_SECRET_KEY=mysecretkey
      - WEBUI_JWT_SECRET_KEY=mysecretkey123456789
      - WEBUI_ALLOW_REGISTRATION=true
      - WEBUI_CORS_ALLOWED_ORIGINS=*
      - OAI_CONFIG_LIST=[{"model":"llama-3-3-70b-instruct:latest","model_max_tokens":4096}]
      - OAI_MAX_TOKENS=4096
      - OPENAI_REQUEST_TIMEOUT=120
      - OPENAI_API_BASE=http://proxy:8000
    volumes:
      - open-webui-data:/app/backend/data
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - webui_network
    depends_on:
      - proxy

  # Service Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - openwebui
    networks:
      - webui_network

networks:
  webui_network:
    driver: bridge

volumes:
  open-webui-data: